import { validateEnvironment } from '../src/config/environment';

describe('validateEnvironment', () => {
  it('provides safe development defaults', () => {
    expect(validateEnvironment({
      OBJECT_STORAGE_ENDPOINT: 'http://127.0.0.1:9000',
      OBJECT_STORAGE_ACCESS_KEY: 'test-access-key',
      OBJECT_STORAGE_SECRET_KEY: 'test-secret-key-value',
      OBJECT_STORAGE_QUARANTINE_BUCKET: 'test-quarantine',
      OBJECT_STORAGE_CLEAN_BUCKET: 'test-clean',
      OPENSEARCH_NODE: 'https://127.0.0.1:9200',
      OPENSEARCH_USERNAME: 'test-search-user',
      OPENSEARCH_PASSWORD: 'test-search-password',
    })).toEqual({
      NODE_ENV: 'development',
      PORT: 3001,
      HOST: '127.0.0.1',
      LOG_LEVEL: 'info',
      TRUST_PROXY: false,
      DATABASE_URL: 'postgresql://niet_erp:niet_erp_dev@127.0.0.1:5432/niet_erp',
      OIDC_ISSUER: 'http://127.0.0.1:8080/realms/niet',
      OIDC_AUDIENCE: 'niet-erp-api',
      OIDC_JWKS_URI: 'http://127.0.0.1:8080/realms/niet/protocol/openid-connect/certs',
      OBJECT_STORAGE_ENDPOINT: 'http://127.0.0.1:9000',
      OBJECT_STORAGE_REGION: 'us-east-1',
      OBJECT_STORAGE_ACCESS_KEY: 'test-access-key',
      OBJECT_STORAGE_SECRET_KEY: 'test-secret-key-value',
      OBJECT_STORAGE_QUARANTINE_BUCKET: 'test-quarantine',
      OBJECT_STORAGE_CLEAN_BUCKET: 'test-clean',
      OPENSEARCH_NODE: 'https://127.0.0.1:9200',
      OPENSEARCH_USERNAME: 'test-search-user',
      OPENSEARCH_PASSWORD: 'test-search-password',
      OPENSEARCH_INDEX: 'niet-erp-search-v1',
      ACADEMIC_POLICY_PUBLICATION_ENABLED: false,
      REGISTRATION_DECISION_ENABLED: false,
      ATTENDANCE_FINALIZATION_ENABLED: false,
      ATTENDANCE_CORRECTION_ENABLED: false,
      FINANCE_POSTING_ENABLED: false,
      FINANCE_REVERSAL_ENABLED: false,
      FINANCE_PROVIDER_POSTING_ENABLED: false,
      FINANCE_RECONCILIATION_APPROVAL_ENABLED: false,
      FINANCE_REFUND_ENABLED: false,
      FINANCE_FEE_STRUCTURE_PUBLICATION_ENABLED: false,
      FINANCE_GOVERNED_DEMAND_ENABLED: false,
      MIGRATION_APPLICATION_ENABLED: false,
      ADMISSION_DECISION_ENABLED: false,
      ADMISSION_DOCUMENT_CHECKLIST_ENABLED: false,
      ADMISSION_DOCUMENT_VERIFICATION_ENABLED: false,
      ADMISSION_DOCUMENT_ENFORCEMENT_ENABLED: false,
      ADMISSION_OFFER_LIFECYCLE_ENABLED: false,
      ADMISSION_CANCELLATION_ENABLED: false,
      ADMISSION_FINANCE_ACCOUNT_ENABLED: false,
      ADMISSION_SEAT_MATRIX_PUBLICATION_ENABLED: false,
      ADMISSION_SEAT_RESERVATION_ENABLED: false,
      ADMISSION_SEAT_ENFORCEMENT_ENABLED: false,
      ADMISSION_MERIT_LIST_PUBLICATION_ENABLED: false,
      ADMISSION_MERIT_SEAT_ENFORCEMENT_ENABLED: false,
      ADMISSION_CONVERSION_EXCEPTION_RESOLUTION_ENABLED: false,
      ADMISSION_CONVERSION_EXCEPTION_WAIVER_ENABLED: false,
      TIMETABLE_PUBLICATION_ENABLED: false,
      STUDENT_CONVERSION_ENABLED: false,
      PROGRAMME_ENROLMENT_ACTIVATION_ENABLED: false,
      STUDENT_HOLD_ENFORCEMENT_ENABLED: false,
      WAITLIST_PROMOTION_ENABLED: false,
      REGISTRATION_WITHDRAWAL_ENABLED: false,
      STUDENT_WITHDRAWAL_ENABLED: false,
    });
  });

  it('rejects an invalid port', () => {
    expect(() => validateEnvironment({
      PORT: '70000',
      OBJECT_STORAGE_ENDPOINT: 'http://127.0.0.1:9000',
      OBJECT_STORAGE_ACCESS_KEY: 'test-access-key',
      OBJECT_STORAGE_SECRET_KEY: 'test-secret-key-value',
      OBJECT_STORAGE_QUARANTINE_BUCKET: 'test-quarantine',
      OBJECT_STORAGE_CLEAN_BUCKET: 'test-clean',
      OPENSEARCH_NODE: 'https://127.0.0.1:9200',
      OPENSEARCH_USERNAME: 'test-search-user',
      OPENSEARCH_PASSWORD: 'test-search-password',
    })).toThrow(
      'Invalid environment configuration',
    );
  });
});
